name: Build hydro table (daily)

on:
  schedule:
    - cron: "10 2 * * *"   # 02:10 UTC daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  hydro:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Camelot (lattice) needs ghostscript; poppler-utils is handy for PDFs
      - name: Install OS deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ghostscript poppler-utils

      - name: Install pip deps
        run: |
          python -V
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build hydrocatchment summary from saved PDFs
        run: |
          set -e
          echo "Repo root:"
          ls -la
          echo "Looking for hydro script…"
          # Prefer v3, then v2, then any *hydro*.py
          SCRIPT="$(ls -1 update_hydro_summary_v3.py 2>/dev/null || true)"
          if [ -z "$SCRIPT" ]; then
            SCRIPT="$(ls -1 update_hydro_summary_v2.py 2>/dev/null || true)"
          fi
          if [ -z "$SCRIPT" ]; then
            SCRIPT="$(ls -1 *hydro*.py 2>/dev/null | head -n1 || true)"
          fi
          if [ -z "$SCRIPT" ]; then
            echo "❌ No hydro script found. Add update_hydro_summary_v3.py to repo root."
            exit 1
          fi
          echo "Using script: $SCRIPT"
          python "$SCRIPT"
          echo "Result files:"
          ls -la hydrocatchment_summary.csv || true

      - name: Commit & push (if changed)
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git add hydrocatchment_summary.csv
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "Update hydrocatchment_summary.csv ($(date -u +%Y-%m-%d))"
            git push
          fi
